"""empty message

Revision ID: a788bd9c1d8a
Revises: 3a7cade3a5b8
Create Date: 2023-09-23 18:29:07.801862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a788bd9c1d8a"
down_revision = "3a7cade3a5b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_groups")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_groups",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="user_groups_group_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_groups_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_groups_pkey"),
    )
    # ### end Alembic commands ###
